Repository yunionio/sqlchemy, pull requests merged in 2019-06, with the labels that each got.

#18 optimization: 1. select subset of fields in subquery 2. add fetch method
  README.md
  conditions.go
  const.go
  debug.go
  fetch.go
  functions.go
  query.go
  sqltest/main.go
  table.go
Labels: approved, lgtm, size/L

#19 query: 改正Count调用
  main_test.go
  query.go
  query_test.go
Labels: approved, lgtm, size/M

#20 query: log not found fields only when DEBUG_SQLCHEMY
  query.go
Labels: approved, lgtm, size/XS

#21 table: 去掉不紧要log
  table.go
Labels: approved, lgtm, size/XS

#22 remove order by restrict
  query.go
Labels: approved, lgtm, size/S

#23 fix: allow text primary key with empty string
  insert.go
Labels: approved, lgtm, size/XS

#24 update support empty primary string
  errors.go
  update.go
Labels: approved, lgtm, size/S

#25 fix: missing white space in insertOrupdate sql
  insert.go
  query.go
  update.go
Labels: size/S

#26 fix: update debug log should show vars
  update.go
Labels: approved, lgtm, size/XS
