Repository yunionio/sqlchemy, pull requests merged in 2019-11, with the labels that each got.

#35 fix: error handling recode to conform with error process standard
  errors.go
  fetch.go
  field_update.go
  insert.go
  query.go
  reflect.go
  update.go
Labels: approved, lgtm

#36 fix: add examples into readme & hide TableNotExists error
  README.md
  errors.go
  sync.go
Labels: lgtm, size/L

#37 sync: log sql with closing semicolon
  sync.go
Labels: lgtm, size/XS
