Repository yunionio/sqlchemy, pull requests merged in 2019-08, with the labels that each got.

#29 feature: sql functions extend
  functions.go
Labels: approved, lgtm, size/M

#30 fix: update no rows returnes sql.ErrNoRows
  update.go
Labels: approved, lgtm, size/XS

#31 将non-pointer boolean column default true的情况由warning改为panic
  column.go
  column_test.go
Labels: approved, lgtm, size/S
