Repository yunionio/sqlchemy, pull requests merged in 2019-04, with the labels that each got.

#8 Bugfix/yousong fix index
  index.go
  query.go
  sync.go
Labels: approved, lgtm, size/M

#9 fix: query.Count returns not only count but also error
  query.go
Labels: approved, lgtm, size/XS

#10 支持insert时初始化created_at及updated_at时间
  insert.go
Labels: approved, lgtm, size/XS

#11 fix: refine the output of update diffs
  update.go
Labels: approved, lgtm, size/S
