Repository yunionio/sqlchemy, pull requests merged in 2020-10, with the labels that each got.

#62 sqltest: make it run again
  sqltest/main.go
Labels: approved, lgtm, size/XS

#63 fix: support sql type of 'tinyint unsigned'
  case.go
  const.go
  functions.go
  parser.go
  sqltest/main.go
  sync.go
  sync_test.go
Labels: approved, lgtm, size/L

#65 fix: remove fatalf logs, as suggested in issue #64
  sync.go
  union.go
Labels: size/S

#66 Make UpdateDiffs stringer return JSON string
  update.go
Labels: lgtm, size/S

#67 fix: make sure the order of fields in SSubQuery
  query.go
Labels: lgtm, size/XS
