Repository yunionio/sqlchemy, pull requests merged in 2021-08, with the labels that each got.

#80 optimized: sql debug format
  debug.go
  query.go
Labels: size/S

#81 add comments
  case.go
  column.go
  conditions.go
  constraint.go
  debug.go
  errors.go
  filter.go
  functions.go
  inc.go
  index.go
  insert.go
  insert_test.go
  query.go
  rawquery.go
  sql.go
  sync.go
  sync_test.go
  table.go
  union.go
  update.go
Labels: size/XL

#82 fix: add more comments
  case.go
  column.go
  conditions.go
  const.go
  debug.go
  errors.go
  fetch.go
  field_update.go
  filter.go
  functions.go
  inc.go
  insert.go
  query.go
  rawquery.go
  sql.go
  sync.go
  table.go
  union.go
  update.go
Labels: size/XL

#83 fix: golint fixes
  column.go
  conditions.go
  debug.go
  errors.go
  fetch.go
  filter.go
  functions.go
  inc.go
  index.go
  insert.go
  parser.go
  query.go
  reflect.go
  sqltest/main.go
  sync.go
  table.go
  tablealias.go
  union.go
Labels: size/L

#84 fix: misspell errors
  column.go
  filter.go
  functions.go
  inc.go
  sync.go
  table.go
Labels: size/S

#85 fix: misspell errors
  column.go
Labels: size/XS

#86 fix: add codecov badget to README
  README.md
Labels: size/XS
