Repository yunionio/sqlchemy, pull requests merged in 2021-11, with the labels that each got.

#91 fix: bugfixes
  backends/clickhouse/clickhouse.go
  backends/mysql/const.go
  backends/mysql/insert_test.go
  backends/mysql/mysql.go
  backends/sqlite/column.go
  backends/sqlite/column_test.go
  backends/sqlite/sqlite.go
  constraint.go
  constraint_test.go
  debug_test.go
  field_update.go
  field_update_test.go
  inc.go
  index.go
  insert.go
  insert_test.go
  sql.go
  update.go
  update_test.go
Labels: size/L

#92 fix: export SetupMockDB
  backends_mock.go
  field_update_test.go
  inc_test.go
  insert_test.go
  query_test.go
  sync_test.go
  update_test.go
Labels: size/S

#93 fix: fix typos in README.md
  README.md
Labels: size/S

#94 fix: stringfield and constfield expression
  functions.go
  query_test.go
Labels: size/M

#95 fix: fail to serialize CompoundColumn
  backends/clickhouse/column.go
  backends/mysql/column.go
  backends/sqlite/column.go
  column.go
  column_test.go
Labels: size/L

#96 fix: union syntax error
  README.md
  backends/mysql/query_test.go
  query_test.go
  union.go
Labels: size/S

#97 fix(sqlchemy): sDBReferer add return DBName func
  sql.go
Labels: size/XS

#98 fix: should use reference in expression of function
  functions.go
  query_test.go
Labels: size/S

#99 fix: sync table recode
  backends.go
  backends/clickhouse/sync.go
  backends/clickhouse/sync_test.go
  backends/mysql/sync.go
  backends/mysql/sync_test.go
  backends/sqlite/sync.go
  backends/sqlite/sync_test.go
  backends_mock.go
  index.go
  sync.go
  sync_test.go
Labels: size/XL

#100 fix: set value of sql string not support any general types
  backends/mysql/sync.go
  backends/sqlite/sync.go
  reflect.go
  reflect_test.go
  sync.go
Labels: size/L

#101 fix: set value from sql string error for boolean
  backends/sqlite/sync.go
  backends/sqlite/sync_test.go
  reflect.go
  reflect_test.go
Labels: size/M

#102 fix: set value from sql string test
  reflect_test.go
Labels: size/XS

#103 fix: reset slice/map before set value of a slice/map column
  reflect.go
Labels: size/XS
