Repository yunionio/sqlchemy, pull requests merged in 2022-04, with the labels that each got.

#114 fix: columns race conditon cause duplicate column name
  field_update.go
  inc.go
  parser.go
  update.go
Labels: lgtm, size/L

#115 preserve UpdateDiffs definition
  update.go
Labels: size/S

#116 fix: insertOrUpdate updates empty fields
  backends_mock.go
  insert.go
  insert_test.go
Labels: size/M

#117 fix: sync table should sync indexes
  backends/mysql/mysql.go
  backends/mysql/sync.go
  backends/sqlite/sqlite.go
  backends/sqlite/sync.go
  table.go
Labels: size/M

#118 fix: add bc function
  functions.go
Labels: size/S

#120 feat: add bc function
  functions.go
Labels: size/S
