Repository yunionio/sqlchemy, pull requests merged in 2023-10, with the labels that each got.

#164 fix: support date_format func
  backends.go
  backends_base.go
  functions.go
Labels: size/S

#165 fix: add copy for sql
  query.go
Labels: size/M

#166 feat: support REGEXP filter
  .circleci/config.yml
  .github/workflows/codecov.yml
  backends.go
  backends_base.go
  conditions.go
  conditions_test.go
  const.go
Labels: size/M

#167 fix: support clickhouse REGEXP filter
  backends.go
  backends/clickhouse/clickhouse.go
  backends/clickhouse/query_test.go
  backends/mysql/query_test.go
  backends/tests/helper.go
  backends_base.go
  conditions.go
  conditions_test.go
  filter.go
Labels: size/L

#168 fix: mysql drop primary should be executed if change happens to primary keys
  backends/mysql/sync.go
Labels: size/M

#169 fix: mysql set bool pointer column failed
  backends/mysql/column.go
Labels: size/XS
